### ISSUE TITLE
Enum\List shares of a hostname

### ISSUE THREAD

**Issue by tomp332** [gentlemanautomaton/smb#1]
Hi there, 
havn't found a way to contact you regarding your Go SMB library.
I have been trying to find a way to list and enumerate all available shares given a hostname\I.P,
is such a thing possible with your library at all? 

thank you

**Comment by zhongguang-cn** [comment]
Why didn't anyone answer? Is the project not going ahead?

**Comment by JoshuaSjoding** [comment]
Sorry for not responding to this when it was originally requested. Development of this SMB server project has been on hiatus for a long while as I've been focused on other things, but I'd _love_ to pick this project back up someday.

If all you're looking for is an SMB client, I highly recommend this project by hirochachacha:

* https://github.com/hirochachacha/go-smb2

I believe it has support for the feature you're looking for:

* https://pkg.go.dev/github.com/hirochachacha/go-smb2#readme-list-share-names
